### ISSUE TITLE
Add in the community and bushiness we support images as thumbnails to fix formatting issues. 

### ISSUE THREAD

**Issue by andrew-macpherson** [net-gain-seo/industrialsafetytrainers#19]

**Comment by mitchtracy11** [comment]
Done:
http://209.126.119.193/~industrialsafety/in-the-community/
http://209.126.119.193/~industrialsafety/business-we-support/

**Comment by mitchtracy11** [comment]
Done: 
http://209.126.119.193/~industrialsafety/constructionsafetytrainers/business-we-support/ 
http://209.126.119.193/~industrialsafety/constructionsafetytrainers/in-the-community/
